//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BM.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BatchManagement
    {
        [Key]
        public int BatchId { get; set; }
        public string BatchName { get; set; }
        public Nullable<int> TotalHours { get; set; }
        public Nullable<int> HoursTaken { get; set; }
    }
}
